### PR TITLE
Includes skinned mesh for vertex color baking

### PR DESCRIPTION
**Pull request by mousedoc**
### Changes
- Fixed to include mesh of SkinnedMeshRenderer
- Fixed a bug where uppercase fbx files were not included in baking

### CODE REVIEW

**Review by Fewes — CHANGES_REQUESTED** [review]
Nice catch with the file extension and nice adding support for skinned meshes, but it looks like it now processes mesh filters twice? Also just to keep the style consistent I'd prefer to not use 'var', plus have brackets for the mesh null checks on #50 and #58. If you fix these things I will happily merge it!

**Comment by mousedoc** [comment]
> Nice catch with the file extension and nice adding support for skinned meshes, but it looks like it now processes mesh filters twice? Also just to keep the style consistent I'd prefer to not use 'var', plus have brackets for the mesh null checks on #50 and #58. If you fix these things I will happily merge it!

Since MeshFilter works with MeshRenderer and 
SkinnedMeshRenderer works without MeshFilter, 
I don't think it will be processed twice as we are concerned. (Please point out if I'm wrong)


```
// idSet == HashSet<int>
int id = skinnedMeshRenderer.sharedMesh.GetInstanceID();
if(idSet.Contains(id))
{
    continue;
}
```

**Comment by mousedoc** [comment]
> > Nice catch with the file extension and nice adding support for skinned meshes, but it looks like it now processes mesh filters twice? Also just to keep the style consistent I'd prefer to not use 'var', plus have brackets for the mesh null checks on #50 and #58. If you fix these things I will happily merge it!
> 
> Since MeshFilter works with MeshRenderer and SkinnedMeshRenderer works without MeshFilter, I don't think it will be processed twice as we are concerned. (Please point out if I'm wrong)
> 
> ```
> // idSet == HashSet<int>
> int id = skinnedMeshRenderer.sharedMesh.GetInstanceID();
> if(idSet.Contains(id))
> {
>     continue;
> }
> ```

Didn't know there was duplicate code
Thanks for pointing out.  😇

**Review by mousedoc — COMMENTED** [review]
Fix code convention, Remove duplicated codes

**Comment by Fewes** [comment]
Thank you! Merged 😄

**Pull request merged**
